title: p5-fundamentals
subtitle: Basics of working with p5.js at IDM

baseurl: "/p5-fundamentals"

# Build settings
markdown: kramdown

# Local dev settings
port: 6300

collections:
  pages:
    output: true
    permalink: :path/

# Defaults
defaults:
  - scope:
      type: "pages"
    values:
      layout: "page"
