title: p5-fundamentals

baseurl: "/p5-fundamentals"

# Build settings
markdown: kramdown

# Local dev settings
port: 6300

collections:
  pages:
    output: true
    permalink: /:path/

# Defaults
defaults:
  - scope:
      path: "_pages"
    values:
      layout: "page"
      permalink: :title/index.html
      type: "tutorial"
