title: p5-fundamentals

baseurl: ""

# Build settings
markdown: kramdown

# Local dev settings
port: 6300

collections:
  pages:
    output: true
    permalink: /:path/

# Defaults
defaults:
  - scope:
      path: "_pages"
    values:
      layout: "page"
